# -*- coding: utf-8 -*-
"""Introduction to Python (History, Why, How).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q2e7akGpS8K8Zta2djiSAJ54qu-Dnxg2

**Day-01**
---

**What is python? Full explanation**

---

### **Agenda**

1. **What is Python?**
2. **History of Python**
3. **Writing and Running your first Python code**
4. **Why name Python?**
5. **Features of Python**
6. **Applications of Python**
7. **Limitations of Python**

---

### **1. What is Python?**

Python is a **General-purpose, Dynamically-typed, and High-level** programming language.

* **Simple Syntax:** It is designed to be highly readable, often looking like plain English statements.
* **Dynamically Typed:** You do not need to declare the data type of a variable (like `int` or `float`) manually; it detects it automatically during execution.

**Daily life example**

When you order food:

1. Bring a burger

2. Bring a cold drink

3. Add ketchup

These are instructions.

In the same way, Python is used to give instructions to a computer.

---

### **2. History of Python**

* **Developed by:** Guido van Rossum.
* **Developed in:** The late 1980s.
* **Released in:** 1991 (Published to the public platform).

### **Why python was created ?**

Old programming languages were difficult and complicated.
Guido wanted to create a language that was simple and easy to read.

So, Python was made beginner-friendly.

**Daily life example**

Like speaking into a microphone and hearing sound from speakers.

Code = Input

Result on screen = Output

print() is used to show something on the screen.

---

### **3. Writing and Running Code**

* **Interactive Mode (Shell):** Using the CMD or Python Shell, you can write a line of code and get instant results (Interpreted nature).
* *Example:* `print("Hello")`


* **Script Mode (IDLE):** Use the **IDLE** (Integrated Development and Learning Environment) to write multi-line programs, save them as `.py` files, and run them all at once.

---

### **4. Why the name "Python"?**

The name does not come from the snake. The developer, Guido van Rossum, was a big fan of a popular BBC comedy television show called **"Monty Python’s Flying Circus."** He wanted a name that was short, unique, and slightly mysterious, so he chose "Python."

**Symbol of snake**

The creator Guido van Rossum, liked this show, so he chose the name **Python**.

Later snake images and logos became part of Python branding because:

**Python** is also the name of a snake...

The snake symbol looks unique and interesting
That is why Python books, logos, and websites often show snakes

---

Like the company “Apple” 🍎

Its name is a fruit, but the company does not sell fruits 😄

---

### **5. Features of Python**

* **Simple and Easy:** Easy to learn for beginners.
* **Free and Open Source:** No cost to use, and the source code is available to everyone.
* **Platform Independent:** You can run the same code on Windows, Linux, or Mac without major changes.
* **Rich Library:** It has a massive collection of libraries for almost every task.
* **Interpreted Language:** It executes code line-by-line, making debugging easier.
* **Embedded & Extensible:** You can put Python code inside C/Java programs (Embedded) or use C/Java code within Python (Extensible).
* **Portable:** Python code run on:

1. Windows
2. Mac
3. Linux


Like a USB that works on different computers.

---

### **6. Applications of Python**

Python is widely used for:

* **Web Development** (Server-side)
* **Game Development**
* **IoT** (Internet of Things)
* **Machine Learning & Artificial Intelligence**
* **Database Connectivity**
* **Network Programming**

---

### **7. Limitations of Python**

* **Mobile Applications:** It is not commonly used or effective for building Android or iOS apps.
* **Speed:** It is slower than compiled languages like C, C++, or Java because it is an interpreted language.

1. **Slow Speed**

Python is slower than languages like C++.

1. Bike = Fast

2. Cycle = Easy

Python is easy but sometimes slower.


**Python is an easy, powerful, and beginner-friendly programming language used in AI, websites, automation, and many modern technologies.**

**Python first code execution**
"""

a = 5
print(a)

print("Hello ")

print("Hello World!")

print("Hello World!")

print('hello Muhammad Bilal')

